export const logoPackage = [
    {
        title: "Basic Logo",
        price: "34.99",
        desc: [
            "3 logo Design concepts",
            "1 Dedicated Designer",
            "2 Revisions",
            "4 Hrs TAT",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
    {
        title: "Ideal Logo",
        price: "74.99",
        desc: [
            "6 Logo Design Concepts",
            "2 Dedicated Designer",
            "Unlimited Revisions",
            "24 - 48 Hrs TAT",
            "Final Files (JPEG, PNG, PDF)",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee",
        ]
    },
    {
        title: "Striking Logo",
        price: "134.99",
        desc: [
            "8 logo Design concepts",
            "3 Dedicated Designer",
            "Unlimited Revisions",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "24/7 Customer Support",
            "Dedicated Account Manager",
            "100% Unique Design Guarantee",
            "100% Satisfaction Guarantee",
        ]
    },
    {
        title: "LOGO STATIONERY",
        price: "149.99",
        desc: [
            "8 logo Design concepts",
            "4 Dedicated Designer",
            "Unlimited Revisions",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "Stationery Design (Business Card, Letterhead, Envelope, MS Word Letterhead)",
        ]
    },
    {
        title: "ILLUSTRATIVE LOGO",
        price: "199.99",
        desc: [
            "1 Illustrative Logo Concept",
            "Concepts By Professional Artist",
            "Unlimited Revisions",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "FREE Icon Design",
            "Dedicated Account Manager",
            "100% Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee",
        ]
    },
    {
        title: "3D LOGO",
        price: "289.99",
        desc: [
            "2 Unique 3D Logo Concepts",
            "Unlimited Revisions",
            "FREE Icon Design",
            "Light Effects And VFX",
            "Concept By Professional Artist",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "100% Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee",
        ]
    },
    {
        title: "MASCOT LOGO",
        price: "449.99",
        desc: [
            "1 Unique Mascot Concept",
            "Unlimited Revisions",
            "Concept By Award-Winning Artist",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "100% Unique Design Guarantee",
            "Dedicated Account Manager",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee",
        ]
    },
    {
        title: "LOGO WEB COMBO",
        price: "499.99",
        desc: [
            "6 Logo Design Concepts",
            "Concepts By Award-Winning Artist",
            "1 Unique Mascot Concept",
            "Unlimited Revisions",
            "24 - 48 Hrs TAT",
            "Final Files (Ai, PSD, EPS, JPEG, PNG, PDF)",
            "Free Bussiness Card Design",
            "Website Development",
            "Up-To 3 Pages Website",
            "Complete W3C Certified HTML",
            "Content Management System",
            "Search Engine Submission",
            "Dedicated Account Manager",
            "100% Unique Design Guarantee",
            "100% Satisfaction Guarantee",
        ]
    },
]
export const websitePackage = [
    {
        title: "BASIC WEBSITE",
        price: "229.99",
        desc: [
            "3 Pages 100% Custom Website Design",
            "Complete Web Development",
            "Unlimited Revisions",
            "3 Royalty-Free Stock Images",
            "1 JQuery Slider Banner",
            "Lead Capturing Form",
            "Complete W3C Certified HTML",
            "Complete Deployment",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee",
            "Combo Add On: $299",
            "24-48 Hrs TAT",
        ]
    },
    {
        title: "STARTER WEBSITE",
        price: "499.99",
        desc: [
            "6 Pages 100% Custom Website Design",
            "Unlimited Revisions",
            "Unlimited Revisions",
            "3 JQuery Slider Banner",
            "Lead Capturing Form",
            "Complete W3C Certified HTML",
            "FREE Google Friendly Sitemap",
            "Complete Website Development",
            "6 Royalty-Free Stock Images",
            "FREE Icon Design",
            "Complete Deployment",
            "Mobile Responsive (Additional Charges)",
            "CMS (Additional Charges)",
        ]
    },
    {
        title: "PROFESSIONAL WEBSITE",
        price: "799.99",
        desc: [
            "10 Pages 100% Custom Website Design",
            "8 Royalty-Free Stock Images",
            "5 JQuery Slider Banner",
            "Complete W3C Certified HTML",
            "Free Icon Design",
            "3 Website Banner Design",
            "Mobile Responsive",
            "Complete Development & Deployment",
            "Unlimited Revisions",
            "Lead Capturing Form",
            "FREE Google Friendly Sitemap",
            "CMS - Content Management System",
            "Complete Deployment",
        ]
    },
    {
        title: "BUSINESS WEBSITE",
        price: "1399.99",
        desc: [
            "20 Pages Custom Website Design",
            "Conceptual And Dynamic Website",
            "Mobile Responsive",
            "CMS - Content Management System",
            "Online Reservation / Appointment Tool",
            "Online Payment Integration",
            "Custom Dynamic Forms",
            "Lead Capturing Form",
            "Striking Hover Effect",
            "Newsletter Subscription(Optional)",
            "Newsfeed Integration",
            "Social Media Integration",
            "Stock Photos",
            "Unique Banner Design",
            "JQuery Slider Banner",
            "Free Google Friendly Sitemap",
            "48 To 72 Hours TAT",
            "Complete Deployment",
            "100 % Satisfaction Guarantee",
            "100 % Unique Design Guarantee",
            "100 % Money - Back Guarantee",
        ]
    },
    {
        title: "INTERACTIVE WEBSITE",
        price: "1799.99",
        desc: [
            "Unlimited Pages",
            "100% Custom Design",
            "Unlimited Revisions",
            "Custom Made, Interactive, Dynamic & High-End Design",
            "Content Management System (CMS)",
            "Multi-User Login",
            "2-Way Login Website",
            "Custom Coding",
            "JQuery Slider Banner",
            "10 Custom Made Banner Design",
            "10 Stock Images",
            "Special Hover Effects",
            "Online Appointment/Scheduling/Online Ordering Integration",
            "Online Payment Integration",
            "Custom Dynamic Forms",
            "Signup Area (For Newsletters, Offers, Etc.)",
            "Search Bar",
            "Live Feeds Of Social Networks Integration",
            "Mobile Responsive",
            "Free Google Friendly Sitemap",
            "Search Engine Submission",
            "Complete W3C Certified HTML",
            "Industry Specified Team Of Expert Designers And Developers",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee"
        ]
    },
    {
        title: "ENTERPRISE WEBSITE",
        price: "3999.99",
        desc: [
            "Complete Custom Design & Development",
            "Dating, Job, Professional Network, Social Network, Restaurant, Medical, Enterprise (Choose One)",
            "Unique, User Friendly, Interactive, Dynamic, High-End UI Design",
            "Unlimited Banner Designs (Includes Interactive Sliding Banners)",
            "Special Hover Effects",
            "Unlimited Stock Images",
            "User Signup & Client/User Dashboard",
            "Custom Coding & Development (Including Content Management System)",
            "Online Appointment/Scheduling/Ordering Integration (if applicable)",
            "Online Payment Integration",
            "Multi-Lingual Support",
            "Custom Dynamic Forms",
            "Shopping Cart Integration (if applicable)",
            "Complete Database Creation",
            "Signup Automated Email Authentication",
            "Web Traffic Analytics Integration",
            "3rd Party API Integrations (if applicable)",
            "Signup Area (For Newsletters, Offers, Etc.)",
            "Search Bar",
            "Live Feeds Of Social Networks Integration",
            "Search Engine Submission",
            "Module-Wise Architecture",
            "Extensive Admin Panel",
            "Award-Winning Team Of Expert Designers And Developers",
            "Complete Deployment",
            "Complete Source Files",
            "Dedicated Project Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Money-Back Guarantee"
        ]
    },
]
export const ecommercePackage = [
    {
        title: "E-COMMERCE LITE WEBSITE",
        price: "799.99",
        desc: [
            "6 Pages Custom Web Design",
            "Complete Development & Deployment",
            "8 Expert Designers & Developers",
            "Up-To 5 Products",
            "Content Management System (CMS)",
            "Full Shopping Cart Integration",
            "Payment Module Integration",
            "Product Reviews",
            "2 Promotional Banners",
            "Unlimited Revisions",
            "Free Icon Design",
            "Free Google Friendly Sitemap",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee",
            "Combo Add On: $299 (Features may vary)"
        ]
    },
    {
        title: "PROFESSIONAL E-COMMERCE WEBSITE",
        price: "1399.99",
        desc: [
            "10 Pages 100% Custom Website Design",
            "Complete Development & Deployment",
            "10 Award-Winning Designers & Developers",
            "Up-To 100 Products (Mini Shopping Cart or Online Ordering Integration)",
            "Online Payment Integration",
            "Product Reviews",
            "Content Management System (CMS)",
            "Interactive Sliding Banners",
            "10 Stock Images",
            "Special Hover Effects",
            "3 Banner Designs",
            "Unlimited Revisions",
            "Custom, Interactive & Dynamic Design",
            "Google Friendly Sitemap",
            "Complete W3C Certified HTML",
            "Search Engine Submission",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee",
            "Combo Add On: $299 (Features may vary)"
        ]
    },
    {
        title: "DYNAMIC E-COMMERCE WEBSITE",
        price: "1799.99",
        desc: [
            "Unlimited Pages 100% Custom Design",
            "Unlimited Revisions",
            "Custom Made, Interactive, Dynamic & High-End Design",
            "Up-To 1000 Products (Full Shopping Cart or Online Ordering Integration)",
            "Online Payment Integration",
            "Multi-User Login",
            "2-Way Login Website",
            "Easy Product Search",
            "Product Reviews",
            "Multi-Lingual Support",
            "Custom Dynamic Forms",
            "Signup Area (For Newsletters, Offers, Etc.)",
            "Search Bar",
            "Content Management System (CMS)",
            "Interactive Sliding Banners (Additional to 10 Custom Banners)",
            "Mobile Responsive",
            "10 Custom Made Banner Designs",
            "10 Stock Images",
            "Special Hover Effects",
            "JQuery Slider Banner (Included in Interactive Sliding Banners)",
            "Complete W3C Certified HTML",
            "Industry Specified Team Of Expert Designers And Developers",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee"
        ]
    },
    {
        title: "BUSINESS E-COMMERCE WEBSITE",
        price: "2499.99",
        desc: [
            "Unlimited Pages 100% Custom Design",
            "Complete Development & Deployment",
            "Award-Winning Designers & Developers",
            "Up-To 2000 Products (Full Shopping Cart or Online Ordering Integration)",
            "Online Payment Integration",
            "Multi-User Login",
            "2-Way Login Website",
            "Easy Product Search",
            "Product Reviews",
            "Multi-Lingual Support (Optional)",
            "Signup Area (For Newsletters, Offers, Etc.)",
            "Search Bar",
            "Content Management System (CMS)",
            "Interactive Sliding Banners",
            "15 Stock Images",
            "Special Hover Effects",
            "Up to 5 Banner Designs",
            "Unlimited Revisions",
            "FREE Icon Design",
            "Google Friendly Sitemap",
            "Custom, Interactive & Dynamic Design",
            "Multi-Lingual (Optional)",
            "Custom Dynamic Forms (Optional)",
            "Live Feeds Of Social Networks Integration",
            "Search Engine Submission",
            "Complete W3C Certified HTML",
            "Industry Specified Team Of Expert Designers And Developers",
            "Complete Deployment",
            "Dedicated Accounts Manager",
            "100% Ownership Rights",
            "100% Satisfaction Guarantee",
            "100% Unique Design Guarantee",
            "100% Money-Back Guarantee"
        ]
    },
]
export const seoPackage = [
    {
        title: "SEO ECONOMY",
        price: "1299",
        desc: [
            "Initial Research Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "Keyword Research & Targeting",
            "10 Selected Keywords",
            "15 Pages Keyword Targeted",
            "On-Page Optimization",
            "On-Page SMM (presumably includes meta tag optimization)",
            "Meta Title Optimization",
            "Meta Description Optimization",
            "Source Code Cleanup & Optimization",
            "Image Optimization",
            "Link Building Optimization",
            "EXML Sitemap Setup",
            "Google Webmaster Code Creation",
            "Google Analytics Code Creation",
            "Image ALT Text",
            "Important HTML Tags (H1, H2, H3)",
            "Robots.Txt Creation",
            "Content Creation & Submission",
            "10 Articles (divided over total months)",
            "15 Blog Posts (divided over total months)",
            "Off-Page Optimization",
            "Social Bookmarking",
            "Slide Share Marketing",
            "Forums/FAQs",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
            "Reporting",
            "Monthly Reporting",
            "On-Phone Reporting (Optional)",
            "Email Reporting",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
    {
        title: "SEO ECONOMY PLUS",
        price: "2399",
        desc: [
            "Initial Research Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "Keyword Research & Targeting",
            "15 Selected Keywords",
            "15 Pages Targeted with Keywords",
            "On-Page Optimization",
            "Includes Meta Tag Optimization",
            "Meta Title Optimization",
            "Meta Description Optimization",
            "Source Code Cleanup & Optimization",
            "Image Optimization",
            "Link Building Optimization",
            "EXML Sitemap Setup",
            "Google Webmaster Code Implementation",
            "Google Analytics Code Implementation",
            "Image Alt Text",
            "Important HTML Tags (H1, H2, H3)",
            "Robots.Txt Creation",
            "Content Creation & Submission (Divided by Months)",
            "20 Articles",
            "30 Blog Posts",
            "5 Infographics (Initial)",
            "Off-Page Optimization",
            "Social Bookmarking",
            "SlideShare Marketing",
            "Forum Participation (Posting & Responding to FAQs)",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
            "5 Image Submissions (Initial)",
            "5 SlideShare Submissions (Initial)",
            "4 Press Releases",
            "10 Infographics Submissions",
            "Reporting",
            "Monthly Reports",
            "Optional: On-Phone Reporting",
            "Email Reports",
            "Additional Features",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
    {
        title: "SEO BUSINESS PRO",
        price: "6999",
        desc: [
            "Initial Research Analysis",
            "Business Analysis",
            "Consumer Analysis",
            "Competitor Analysis",
            "Keyword Research & Targeting",
            "25 Selected Keywords",
            "25 Pages Targeted with Keywords",
            "On-Page Optimization",
            "Includes Meta Tag Optimization",
            "Meta Title Optimization",
            "Meta Description Optimization",
            "Source Code Cleanup & Optimization",
            "Image Optimization",
            "Link Building Optimization",
            "EXML Sitemap Setup",
            "Google Webmaster Code Implementation",
            "Google Analytics Code Implementation",
            "Image Alt Text",
            "Important HTML Tags (H1, H2, H3)",
            "Robots.Txt Creation",
            "Content Creation & Submission (Divided by Months)",
            "40 Articles",
            "60 Blog Posts",
            "15 Infographics (Initial)",
            "Off-Page Optimization",
            "Social Bookmarking",
            "SlideShare Marketing",
            "Forum Participation (Posting & Responding to FAQs)",
            "Link Building",
            "Directory Submission",
            "Local Business Listings",
            "1 Initial Image Submission",
            "1 Initial SlideShare Submission",
            "6 Press Releases",
            "15 Infographics Submissions",
            "Reporting",
            "Monthly Reports",
            "Optional: On-Phone Reporting",
            "Email Reports",
            "Additional Features",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
]
export const smmPackage = [
    {
        title: "BASIC",
        price: "249.99",
        desc: [
            "Account Management (2 Accounts)",
            "Campaign Creation (1)",
            "Facebook Business Manager Set Up",
            "Custom Audience Creation",
            "Facebook Analytics Report Creation",
            "Ad Campaign Monitoring",
            "Customization of Ad Placements",
            "Traffic Monitoring",
            "Monthly Report",
            "Audience Research",
            "Instagram Ads Creative Creation & Design",
            "Instagram Ads Monitoring & Management"
        ]
    },
    {
        title: "PROFESSIONAL",
        price: "499",
        desc: [
            "Account Management (3 Accounts)",
            "Campaign Creation (3)",
            "Facebook Business Manager Set Up",
            "Pixel Installation",
            "Custom Conversion Creation",
            "Remarketing",
            "Creation of Automated Rules",
            "Facebook Analytics Report Creation",
            "Ad Campaign Monitoring",
            "Instant Experience Ads Creation",
            "Customization of Ad Placements",
            "Traffic Monitoring",
            "Monthly Report",
            "Audience Research",
            "Instagram Ads: Creative Creation, Design & Monitoring & Management",
            "**Campaign Manager Account Set Up",
            "Creation of Custom Conversions",
            "Ads Monitoring",
            "YouTube Ads Account Set Up",
            "Skippable In-Stream Ads",
            "Non-Skippable In-Stream Ads",
            "Bumper Ads",
            "Detailed & Custom Audience Creation",
            "A/B Testing of Targeting",
            "Remarketing Video Ads",
            "Tweet Engagement Ads",
            "Awareness Ads",
            "Follower Ads",
            "Audience Creation"
        ]
    },
    {
        title: "ADVANCED",
        price: "899",
        desc: [
            "Account Management (5 Accounts)",
            "Creation Of Campaign (6)",
            "Facebook Business Manager Set Up",
            "Pixel Installation",
            "Custom Conversion Creation",
            "Remarketing",
            "Custom Audience Creation",
            "Creation Of Automated Rules",
            "Facebook Analytics Report Creation",
            "Ad Campaign Monitoring",
            "Catalogue Creation",
            "Dynamic Ads Creation",
            "Instant Experience Ads Creation",
            "Customization Of Ad Placements",
            "A/B Testing Of Ad Set, Creative And Placement",
            "Carousel And Collection Ads",
            "Traffic Monitoring",
            "Monthly Report",
            "Audience Research",
            "Instagram Ads Creative Creation & Design",
            "Instagram Ads Monitoring And Management",
            "Campaign Manager Account Set Up",
            "LinkedIn Insight Tag Installation",
            "Creation Of Custom Conversion",
            "Ads Monitoring",
            "Youtube Ad Account Set Up",
            "Skippable In-Stream Ads",
            "Non-Skippable In-Stream Ads",
            "Bumper Ads",
            "Discovery Ads",
            "Youtube Video Sequence Ads",
            "Detailed Audience Creation",
            "A/B Testing Of Targeting",
            "Remarketing Video Ads",
            "Video Ads With Promotion Of Your Products",
            "Tweet Engagement Ads",
            "Video Or GIF View Ads",
            "Awareness Ads",
            "Website Conversion Ads",
            "In-Stream Video View Ads",
            "Follower Ads",
            "App Install Ads",
            "App Reengagement",
            "Audience Creation"
        ]
    },
]
export const videoPackage = [
    {
        title: "ABSOLUTE VIDEO",
        price: "499.99",
        desc: [
            "30s Duration",
            "Professional Script",
            "Storyboard",
            "Custom Graphics & Characters",
            "Animation & SFX",
            "Background Music",
            "Background Image",
            "Watermark Logo",
            "Resolution – HD",
            "Voice Over Recording",
            "Sync Voice Over",
            "Unlimited Revisions",
            "Turnaround Time 2-3 Weeks",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
    {
        title: "OPTIMUM VIDEO",
        price: "999.99",
        desc: [
            "Up-To 60s Duration",
            "Professional Script",
            "Storyboard",
            "Custom Graphics & Characters",
            "Animation & SFX",
            "Background Music",
            "Background Imagery",
            "Watermark Logo",
            "Resolution – HD",
            "Voice Over Recording",
            "Sync Voice Over",
            "Unlimited Revisions",
            "Turnaround Time 3-4 Weeks",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
    {
        title: "ULTIMATE VIDEO",
        price: "1499.99",
        desc: [
            "Up-To 120s Duration",
            "Professional Script",
            "Storyboard",
            "Custom Graphics & Characters",
            "Animation & SFX",
            "Background Music",
            "Background Imagery",
            "Watermark Logo",
            "Resolution – HD",
            "Voice Over Recording",
            "Sync Voice Over",
            "Unlimited Revisions",
            "Turnaround Time 4-6 Weeks",
            "Dedicated Account Manager",
            "Unique Design Guarantee",
            "24/7 Customer Support",
            "100% Satisfaction Guarantee"
        ]
    },
]
export const brandingPackage = [
    {
        title: "STARTUP COLLATERAL",
        price: "99.99",
        desc: [
            "2 Stationery Design Set",
            "FREE Fax Template",
            "Print Ready Formats",
            "UNLIMITED Revisions",
            "100% Satisfaction Guarantee",
            "100% Money Back Guarantee"
        ]
    },
    {
        title: "COLLATERAL CLASSIC",
        price: "199.99",
        desc: [
            "2 Stationery Design Set",
            "UNLIMITED Revisions",
            "Flyer Design",
            "Brochure Design (Bi-Fold/Tri-Fold)",
            "100% Satisfaction Guarantee",
            "100% Money Back Guarantee"
        ]
    },
    {
        title: "PREMIUM COLLATERAL",
        price: "399.99",
        desc: [
            "Hat Design",
            "Invoice Design",
            "Email Signature Design",
            "2 Stationery Design Set",
            "Packaging Design",
            "UNLIMITED Revisions",
            "T-Shirt Design",
            "100% Satisfaction Guarantee",
            "100% Money Back Guarantee"
        ]
    },
]
export const hostingPackage = [
    {
        title: "1 Year Bronze Website Hosting And 6 Months Maintenance",
        price: "699.99",
        desc: [
            "Dedicated Hosting Server",
            "150 GB Storage",
            "8 GB Ram",
            "Unmetered Traffic",
            "Standard SSL Certificate",
            "3 Free Email Accounts",
            "General Features (2 Hours / Month):",
            "Text Updating (Client Supplied)",
            "Fixing Broken Links (5/Month)",
            "Optimization of Client Supplied Images",
            "Setting Up Email",
            "24/7 Support Email/Ticket"
        ]
    },
    {
        title: "1 Year Silver Website Hosting And 6 Months Maintenance",
        price: "899.99",
        desc: [
            "Dedicated Hosting Server",
            "1 Free Domain",
            "150 GB Storage",
            "8 GB Ram",
            "Unmetered Traffic",
            "Unlimited Websites And Databases",
            "Standard SSL Certificate",
            "5 Free Email Accounts",
            "General Features (5 Hours / Month):",
            "Text Updating (Client Supplied)",
            "Fixing Broken Links (5/Month)",
            "Optimization of Client Supplied Images",
            "Setting Up Email",
            "24/7 Support Email/Ticket"
        ]
    },
    {
        title: "1 Year Gold Website Hosting & 1 Year Website Maintenance",
        price: "1199.99",
        desc: [
            "Dedicated Hosting Server",
            "2 Free Domains",
            "250 GB Storage",
            "12 GB Ram",
            "Unmetered Traffic",
            "Unlimited Websites And Databases",
            "Standard SSL Certificate",
            "10 Free Email Accounts",
            "General Features (10 Hours / Month):",
            "Text Updating (Client Supplied)",
            "Fixing Broken Links (5/Month)",
            "Optimization of Client Supplied Images",
            "Setting Up Email",
            "24/7 Support Email/Ticket"
        ]
    },
]

